Fixed bug regarding manga volumes in discord rich presence
MALSync/MALSync pull request #1019
Opened 2022-01-10 05:41 UTC by Gamesmes90

I found a bug regarding the rich presence. 

I was testing the extension with Komga and found out that if the manga has "volume" or "volumes" tag, the rich presence will display "Chapter: 0 of X".

![image](https://user-images.githubusercontent.com/30806751/148722297-adf1063c-5a87-4466-ad04-68040715727f.png)

Checking for the volumes fixes the issue. I also called the "UI_Volume" directly.

![image](https://user-images.githubusercontent.com/30806751/148722399-f92ff2c6-0c9d-43a0-b30b-d243eb035523.png)

2022-01-10 06:33 UTC, henrik9999 requested changes
There are pages that have volume and chapter at the same time I would prefer that it shows the chapter number or maybe both instead then

2022-01-10 07:22 UTC, Gamesmes90 commented
> There are pages that have volume and chapter at the same time I would prefer that it shows the chapter number or maybe both instead then

Sorry, I didn't know that. I can try adding both. What pages can show both?

2022-01-11 04:24 UTC, Gamesmes90 commented
Now it shows both volume and chapter number.

![image](https://user-images.githubusercontent.com/30806751/148880568-1137fce9-1473-464d-bd89-0432dcc4f0ab.png)

I changed "of" with a slash to save space when it shows both.

2022-01-11 09:14 UTC, lolamtisch commented
I think the chapter should be in front, as it is the more important metric. Would be annoying if it would cut of.

2022-01-12 05:27 UTC, Gamesmes90 commented
Done.

![image](https://user-images.githubusercontent.com/30806751/149068992-af9bb6ad-10ad-4657-acfd-3296a9444a6b.png)

2022-01-17 10:16 UTC, lolamtisch commented
I cleaned up the code. 
I removed the untranslated "of". 
And the totalchap/volume is only shown if there is one as the ? wasnt that helpfull in the presence

2022-01-17 10:30 UTC, merged