Add Disney +
MALSync/MALSync pull request #1343
Opened 2022-10-17 22:13 UTC by HugoLeBoennec

I'm adding **Disney+** with:

1. Overview Page w/ List
2. Sync Page
3. Test
4. Some king of mutli lang Url support

First time doing a Fork and Pull Request, i will look into your revisions 😀

2022-10-18 20:54 UTC, HugoLeBoennec commented
So test can't be run headless because you need to be log and geoloc in specific country (UK for testing)

2022-11-18 20:52 UTC, Celuni commented
I'd love to have this approved.
Let me know if you need my disney account with active subscription for testing purposes and where to contact you if so.

2022-11-18 20:58 UTC, lolamtisch commented
It is a bit more difficult as there are no anime on disney plus germany.

2022-11-18 21:01 UTC, HugoLeBoennec commented
> It is a bit more difficult as there are no anime on disney plus germany.

I use a VPN because for the moment my country too

2022-11-18 21:01 UTC, lolamtisch requested changes

2022-11-18 21:01 UTC, lolamtisch commented on src/pages/list.json
> +  {
Please dont commit changes to this file

2022-11-27 11:46 UTC, HugoLeBoennec commented
How do I rollback the files not to be pushed @lolamtisch

2022-11-27 12:50 UTC, lolamtisch commented
If you want to do it clean then cherry pick with force push.

2022-12-20 15:41 UTC, HugoLeBoennec commented
I finally did It

2022-12-20 15:43 UTC, HugoLeBoennec commented
But before merging, i saw that Disney juste add "season", so i need to integre it

2023-04-27 14:57 UTC, closed without merging