Add AnimeSub.LT page
MALSync/MALSync pull request #1840
Opened 2023-06-08 17:10 UTC by PcmKomanda

2023-06-08 17:13 UTC, henrik9999 requested changes

2023-06-08 17:13 UTC, henrik9999 commented on src/pages/AnimeSub/main.ts
> +function malId(provider) {
this function isnt used

2023-06-08 17:17 UTC, PcmKomanda commented on src/pages/AnimeSub/main.ts
> +function malId(provider) {
Whoops. You're right. 😅

2023-06-08 17:18 UTC, henrik9999 commented on src/pages/AnimeSub/main.ts
> +function malId(provider) {
now you are not using the anilist link

2023-06-08 17:20 UTC, henrik9999 commented
the site has anime and manga so you have to set the type in the init function accordingly `page.type = 'anime'` or `page.type = 'manga`

2023-06-08 17:32 UTC, PcmKomanda commented
> page.type = 'anime' or page.type = 'manga'

Property 'type' does not exist on type 'SyncPage'

2023-06-09 08:04 UTC, lolamtisch commented
Should be `AnimeSub.type` what can be set.
https://github.com/MALSync/MALSync/blob/master/src/pages/Proxer/main.ts#L119

2023-08-16 01:22 UTC, closed without merging