Added ColoredManga
MALSync/MALSync pull request #1997
Opened 2023-08-22 20:47 UTC by fabiomurru96

Added [ColoredManga](https://coloredmanga.com/) to supported pages, it derives from Isekaiscan as they're both implemented using [madara](https://github.com/guendev/madara).

I've slightly refactored Isekaiscan's page to be able to clone and override it (took inspiration from [MangaHere](https://github.com/MALSync/MALSync/blob/master/src/pages/MangaHere/main.ts))

---

Related Issue
- https://github.com/MALSync/MALSync/issues/977

2023-08-22 20:52 UTC, fabiomurru96 commented
The Isekaiscan diff is pretty bad here in github, if it can help reviewing these are the real changes 

<details>

<summary>Click here to see image</summary>

![image](https://github.com/MALSync/MALSync/assets/20525680/a51fd99d-eb4f-4588-9a37-0003f1e34816)
</details>

2023-08-27 11:47 UTC, lolamtisch requested changes

2023-08-27 11:47 UTC, lolamtisch commented on src/pages/ColoredManga/main.ts
> +import { pageInterface } from '../pageInterface';
Not all Chapters are recognized

https://coloredmanga.com/mangas/medaka-box/volume-12/box-106/
https://coloredmanga.com/mangas/spy-x-family-colour/volume-10-bw/mission-67-2-bw/
https://coloredmanga.com/mangas/eng-rurouni-kenshin/volume-28/act-255-finale/

2023-08-27 11:47 UTC, lolamtisch commented on src/pages/ColoredManga/main.ts
> +const clone = getInter();
Title could be cleaned up a bit to make the matching with mal better.
Full Color
{Official TL}
(EN)

2023-11-04 20:15 UTC, closed without merging