add manhuaus
MALSync/MALSync pull request #2132
Opened 2023-11-10 11:44 UTC by MareksKing

Request to add manhuaus

2023-11-10 12:56 UTC, henrik9999 requested changes

2023-11-10 12:56 UTC, henrik9999 commented on src/pages/ManhuaUS/main.ts
> +import { util } from "chai";
Why is this imported

2023-11-10 12:56 UTC, henrik9999 commented on src/pages/playerUrls.js
> +  manhuaus:{
This is a manga page it should not need player urls

2023-11-10 12:59 UTC, henrik9999 commented on src/pages/ManhuaUS/main.ts
> +export const manhuaus: pageInterface = {
The name and export should be written ManhuaUS

2023-11-17 16:16 UTC, henrik9999 commented
`npm run lint:fix`

2023-11-19 14:40 UTC, lolamtisch requested changes

2023-11-19 14:40 UTC, lolamtisch commented on src/pages/ManhuaUS/meta.json
> +        "match": ["*//manhuaus.com/*"]
You forgot the `:`
["*://manhuaus.com/*"]

2023-11-19 14:40 UTC, lolamtisch commented on src/pages/ManhuaUS/main.ts
> +    list: {
The list handling does not work

2023-11-19 14:40 UTC, lolamtisch commented on src/pages/ManhuaUS/main.ts
> +          'div.entry-header.header > div > div.select-pagination > div.nav-links > div.nav-next > a.next_page',
Would be nice to make this less specific. Because a small page change would break this selector

2024-01-21 13:16 UTC, closed without merging