AnimeFenix
MALSync/MALSync pull request #2310
Opened 2024-02-29 01:30 UTC by Keiser04

I still have to figure out how to add this because I don't understand how to do it.
![image](https://github.com/MALSync/MALSync/assets/146493916/71fcea3f-e65a-42a0-974b-9bbd4b39b776)

2024-02-29 02:27 UTC, lolamtisch requested changes

2024-02-29 02:27 UTC, lolamtisch commented on src/pages/AnimeFenix/main.ts
> +      let titleElement = document.querySelector("body > div.hero.is-fullheightX > section > div > div > div.column.is-12-mobile.is-8-tablet.is-9-desktop > h1");
Selector to specific. Breaks with every page change

2024-02-29 02:27 UTC, lolamtisch commented on src/pages/AnimeFenix/main.ts
> +      let titleElement = document.querySelector("body > div.hero.is-fullheightX > section > div > div > div.column.is-12-mobile.is-8-tablet.is-9-desktop > h1");
Duplicate code

2024-02-29 02:27 UTC, lolamtisch commented on src/pages/AnimeFenix/main.ts
> +export interface pageState {
What does this do?

2024-02-29 02:28 UTC, lolamtisch commented
You need to setup the overiview correctly with the uiSelector correctly setuped

2024-02-29 11:35 UTC, Keiser04 commented
> You need to setup the overiview correctly with the uiSelector correctly setuped

but is not optional?
![image](https://github.com/MALSync/MALSync/assets/146493916/65c46ac6-b5d1-4e2d-aaa6-1667851b7de1)
![image](https://github.com/MALSync/MALSync/assets/146493916/af6664e6-87aa-40c0-9cb6-596741806572)
you have a easy example?

2024-02-29 12:45 UTC, lolamtisch commented
Yes it is optional. But if you want the ui you will need to add the overview page, but you dont need to.

sync page: the page with the player/video

2024-02-29 12:47 UTC, lolamtisch commented
Yes it is optional. But if you want the ui you will need to add the overview, but you dont need to. If you only want to implement syncing of the watched ep you dont need to overview

sync page: video page
overview page: the page where the list of episodes is

Simple example: https://github.com/MALSync/MALSync/blob/master/src/pages/Gogoanime/main.ts

2024-02-29 16:22 UTC, Keiser04 commented
> Yes it is optional. But if you want the ui you will need to add the overview, but you dont need to. If you only want to implement syncing of the watched ep you dont need to overview
> 
> sync page: video page overview page: the page where the list of episodes is
> 
> Simple example: https://github.com/MALSync/MALSync/blob/master/src/pages/Gogoanime/main.ts

ok i will try this nigth

2024-03-02 16:39 UTC, Keiser04 commented
> Yes it is optional. But if you want the ui you will need to add the overview, but you dont need to. If you only want to implement syncing of the watched ep you dont need to overview
> 
> sync page: video page overview page: the page where the list of episodes is
> 
> Simple example: https://github.com/MALSync/MALSync/blob/master/src/pages/Gogoanime/main.ts

![image](https://github.com/MALSync/MALSync/assets/146493916/047b4c71-7907-4841-b7a4-948581d2fbba)
I added it but I can't get the list of episodes, I don't know what I can do to fix it, sorry.

2024-03-05 00:21 UTC, Keiser04 commented
@lolamtisch what i do? another push?

2024-03-05 11:02 UTC, lolamtisch requested changes

2024-03-09 15:12 UTC, Keiser04 commented
@lolamtisch I surrendered on the overview . I only have this left that I didn't know what you meant.

{
  "urls": {
    "match": ["*://animefenix.tv/*"]
  }
}

2024-03-11 14:12 UTC, Keiser04 commented
@lolamtisch can you watch if all is correct?

2024-03-11 14:53 UTC, Keiser04 reviewed
i give up whit overview

2024-03-11 14:53 UTC, Keiser04 commented on src/pages/AnimeFenix/main.ts
> +      return AnimeFenix.sync.getTitle(url);
i give up whit overview

2024-03-11 14:53 UTC, Keiser04 commented on src/pages/AnimeFenix/main.ts
> +    getOverviewUrl: (url: string) => {
i give up whit overview

2024-03-11 14:53 UTC, Keiser04 commented on src/pages/AnimeFenix/meta.json
> +  "urls": {
what do you mean @lolamtisch ?

2024-03-11 14:53 UTC, Keiser04 commented on src/pages/AnimeFenix/tests.json
> +      "url": "https://animefenix.tv/ver/youkoso-jitsuryoku-shijou-shugi-no-kyoushitsu-e-3rd-season-9",
i give up whit overview

2024-03-11 23:43 UTC, lolamtisch commented on src/pages/AnimeFenix/meta.json
> +  "urls": {
Like mentioned in the old PR

> Search url is missing
>
> Example: https://github.com/MALSync/MALSync/blob/master/src/pages/AnimeXin/meta.json#L2

2024-03-12 00:00 UTC, lolamtisch requested changes

2024-03-12 00:00 UTC, lolamtisch commented on src/pages/AnimeOnegai/meta.json
> -{
Please dont commit unrelated files

2024-03-12 00:00 UTC, lolamtisch commented on src/pages/OtakuFR/tests.json
> -{
Please dont commit unrelated files

2024-03-12 00:00 UTC, lolamtisch commented on src/pages/AnimeFenix/main.ts
> +    getTitle: (url: string) => {
title wrong

2024-03-12 00:00 UTC, lolamtisch commented on src/pages/AnimeFenix/main.ts
> +  isOverviewPage: (url: string) => {
Not used

2024-03-12 00:00 UTC, lolamtisch commented on src/pages/AnimeFenix/main.ts
> +  init: (page) => {
Style import is missing

2024-03-12 00:00 UTC, lolamtisch commented on src/pages/AnimeFenix/main.ts
> +        page.url.split('/')[3] !== 'animes'
Not necessary as no overview

2024-03-12 00:45 UTC, Keiser04 commented on src/pages/OtakuFR/tests.json
> -{
srry i download all to remplace

2024-03-12 22:41 UTC, closed without merging