New Page AnimesOnline
MALSync/MALSync pull request #2392
Opened 2024-05-08 01:33 UTC by Martins-74

Added a new page animesonline

2024-05-14 19:53 UTC, lolamtisch requested changes

2024-05-14 19:53 UTC, lolamtisch commented on src/pages/AnimesOnline/main.ts
> +    },
duplicated code. One could just call `return AnimesOnline.sync.getTitle(url);`

2024-05-14 19:53 UTC, lolamtisch commented on src/pages/AnimesOnline/main.ts
> +    },
More duplicated code. You can just call the functions of the sync section

2024-05-14 19:53 UTC, lolamtisch commented on src/pages/AnimesOnline/main.ts
> +  domain: 'animesonline.in',
Please use `https://animesonline.in`

2024-05-14 19:53 UTC, lolamtisch commented on src/pages/AnimesOnline/main.ts
> +      alert('MAL-SYNC: Cant find target src video, please refresh the page and try again!');
Alerts are a bit hard. Please use 
```
utils.flashm(`MAL-SYNC: Cant find target src video, please refresh the page and try again!`, {
    error: true,
    type: 'error',
  });
```

2024-05-18 11:05 UTC, Martins-74 commented
Requested changes done

2024-05-21 09:40 UTC, merged