Ranobelib sync
MALSync/MALSync pull request #2631
Opened 2024-10-07 16:34 UTC by DFreezerR

Part of #2061 [3/5]
RanobeLib - LN + WN website.
Did almost everything based on #2624 
Includes api.ts file from #2606 
Had to modify internal files a bit to allow search + correction search work with SHIKI sync mode and novel types. Because as it is, there's no way to search novels on SHIKI sync mode. To do it, shikimori have a separate page `/ranobes` while other providers use `/manga` page to track both manga and novels. To mess as less as I could with internals I used `options` parameter in `searchInterface` and passed it down from  `src/_provider/Search/vueSearchClass.ts` with the novel type check to determine if the page in novel type. I "could've" add another page type in `pageInterface` but that would've meant I will need to change types almost everywhere, and to reduce changes I used already existed `options` and `this.type` in  `src/_provider/Search/searchClass.ts` and passed it down to search function. Moreover the only provider that uses this check is shikimori so there's no need to change every search function.
Additionally changed how `src/_provider/Search/searchClass.ts` works a bit since to search for novel more precisely you need to include both 'novels' and 'light novels' + added filter to search only for either of them.

As I tested, there's not much novels on either providers, and you WILL encounter situation where you either have to specify novel by correction search or to use local sync. Or you can add your novel on MAL yourself (on on any other provider if there is none). To me, the probability of novel to exist was around 60%, so - <h4>If you gonna use it, always check if novel was set correctly in either MAL-Sync uiSelector on overview page or using float button in bottom right</h4>

Also,
<h3>Like the other PRs(#2606 + #2624) this one takes access tokens from authorized user to make API calls. I guess there "might" be security problems if someone tries something bad this way. And if this breaches this projects ethical or security conducts, please tell. Just keeping everyone informed just in case.</h3>

2025-01-28 23:42 UTC, closed without merging

2025-01-28 23:44 UTC, DFreezerR commented
uh...

2025-02-10 17:33 UTC, lolamtisch requested changes
Sorry for the late review. Was too bussy and changes to the search always need thorough review.

2025-02-10 17:33 UTC, lolamtisch commented on src/_provider/Search/components/search.vue
> +    options: {
Remove as the filtering by novel happens afterwards on the "isNovel". This allows for the automatching to only match novels. The user facing search Ui does not have the filtering, making it possible for the user to select an novel for manga pages if they have one for some reason.

2025-02-10 17:33 UTC, lolamtisch commented on src/_provider/Search/components/search.vue
> +        normalSearch(this.searchKeyword, this.type, this.options).then(items => {
revert

2025-02-10 17:33 UTC, lolamtisch commented on src/_provider/Search/correctionApp.vue
> +        :options="options"
revert

2025-02-10 17:33 UTC, lolamtisch commented on src/_provider/Search/correctionApp.vue
> +    options: {},
revert

2025-02-10 17:33 UTC, lolamtisch commented on src/_provider/Search/vueSearchClass.ts
> +      this.vueInstance.options = {
revert

2025-02-10 17:33 UTC, lolamtisch commented on src/_provider/Shikimori/search.ts
>  export const search: searchInterface = async function (
This is too much of a workaround. Better to revert this.

As far as I see the real fix would be to migrate Shikimori to the graphql endpoint, which does not have the novel destinction anymore. But that would be better in a seperate PR

2025-02-10 17:33 UTC, lolamtisch commented on src/utils/Search.ts
> +  options = {},
revert

2025-02-10 20:43 UTC, DFreezerR commented on src/_provider/Search/searchClass.ts
>      if (this.type === 'novel') {
True, you are right

2025-02-10 20:43 UTC, DFreezerR commented on src/_provider/Search/searchClass.ts
> +    // REVIEW - Proposal, can we rename every 'titel' to 'title' except DE locale?
Done

2025-02-10 20:44 UTC, DFreezerR commented on src/_provider/Search/components/search.vue
> +    options: {
Reverted whole shikimori changes

2025-02-10 20:44 UTC, DFreezerR commented on src/_provider/Search/components/search.vue
> +        normalSearch(this.searchKeyword, this.type, this.options).then(items => {
Reverted whole shikimori changes

2025-02-10 20:44 UTC, DFreezerR commented on src/_provider/Search/correctionApp.vue
> +        :options="options"
Reverted whole shikimori changes

2025-02-10 20:44 UTC, DFreezerR commented on src/_provider/Search/correctionApp.vue
> +    options: {},
Reverted whole shikimori changes

2025-02-10 20:44 UTC, DFreezerR commented on src/_provider/Search/vueSearchClass.ts
> +      this.vueInstance.options = {
Reverted whole shikimori changes

2025-02-10 20:44 UTC, DFreezerR commented on src/utils/Search.ts
> +  options = {},
Reverted whole shikimori changes

2025-02-10 20:46 UTC, DFreezerR commented on src/_provider/Search/searchClass.ts
> +          if (This.type === 'novel') {
I can think of something like this:
```ts
if (This.type === 'manga' || This.type === 'novel') {
  const typeCheck = response.responseText.split(`href="${link}" id="si`)[1].split('</tr>')[0];
  const linkIsNovel = typeCheck.indexOf('Novel') !== -1;

  if ((This.type === 'manga' && linkIsNovel) || (This.type === 'novel' && !linkIsNovel)) {
    logger.log(`${linkIsNovel ? 'Novel Found' : 'Novel Not found'} check next entry`);
    return handleResult(response, i + 1, This);
  }
}
```
?

2025-02-10 22:34 UTC, DFreezerR commented on src/_provider/Shikimori/search.ts
>  export const search: searchInterface = async function (
Btw I have a test implementation of graphql, can send a PR so you can check if this is worth working with

2025-02-11 00:31 UTC, lolamtisch commented on src/_provider/Shikimori/search.ts
>  export const search: searchInterface = async function (
I did not check it out in detail, but if it uses the same Auth token I do not see an issue with mixing it. Specially because I imagine it is easy to split. The user lists and search can use graph and the single can use the rest API, as it handles novel IDs at the manga endpoint too.

2025-02-11 01:07 UTC, DFreezerR commented on src/_provider/Shikimori/search.ts
>  export const search: searchInterface = async function (
got it

2025-02-11 17:37 UTC, lolamtisch approved these changes