Add AnimeOnsen
MALSync/MALSync pull request #984
Opened 2021-11-30 17:23 UTC by mist8kengas

2021-12-16 10:20 UTC, lolamtisch requested changes

2021-12-18 14:43 UTC, mist8kengas commented on src/pages/AnimeOnsen/meta.json
> +    "exclude": ["*://*.animeonsen.xyz/*", "*://*.animeonsen.xyz/account/*", "*://*animeonsen*.*/*"]
It's to prevent extension being loaded on API and CDN subdomains

2021-12-18 15:56 UTC, mist8kengas commented
Simplified `isSyncPage(url)` function, implemented `isOverviewPage(url)`, and added `.ready()` method in `init(page)`.

2021-12-19 16:58 UTC, lolamtisch approved these changes
Looks good

2021-12-19 16:58 UTC, merged